---
title: "hw2"
author: "Sridhar Sampath"
date: "9 February 2018"
output: pdf_document
---

1. Professional Education by State [20 points]

```{r}
library(ggplot2)
library(dplyr)
library(knitr)
#install.packages("magrittr")
library(magrittr)
data(mpg)

mpg_mfr_summary = mpg %>% group_by(manufacturer) %>% 
                    summarize(minHwy = min(hwy), 
                    q1Hwy = quantile(hwy, 0.25), 
                    meanHwy = mean(hwy), 
                    medianHwy = median(hwy), 
                    q3Hwy = quantile(hwy, 0.75), 
                    maxHwy = max(hwy),
                    stdHwy = sd(hwy))
mpg_mfr_summary
mpg_mfr_summary = data.frame(mpg_mfr_summary)
mpg_mfr_summary = mpg_mfr_summary[order(-mpg_mfr_summary$medianHwy),]
row.names(mpg_mfr_summary) = NULL
kable(mpg_mfr_summary)

ggplot(mpg, aes(x=reorder(manufacturer, hwy), y=hwy)) + 
  geom_boxplot(aes(fill=manufacturer)) + 
  coord_flip() +
  labs(x="Manufacturer", y="Highway Mpg", title="Highway Mpg by Manufacturer Boxplot")

```
```{r}
data(midwest)
ggplot(midwest , aes(reorder(state, -percprof, mean) , percprof)) + 
    geom_boxplot(aes(color=state)) +
    coord_flip()+
    scale_x_discrete("state") +
    ggtitle("% of professionals by state")

# calculate the mean and standard derivation of "percprof" for each state
state_unique=unique(midwest$state) # find all the states in column midwest$state

# calculate mean and standard derivation for each state
mean_Q1=c(1:length(state_unique)) 
SD_Q1 =c(1:length(state_unique))
Median_Q1=c(1:length(state_unique))
names(mean_Q1)=state_unique
names(SD_Q1)=state_unique
names(Median_Q1)=state_unique
j=1
for (i in state_unique){
  mean_Q1[j]=mean(midwest$percprof[midwest$state==i])
  SD_Q1 [j] =sd(midwest$percprof[midwest$state==i])
  Median_Q1 [j]= median(midwest$percprof[midwest$state==i])
  j=j+1
}
stat_Q1=data.frame(state_unique,mean_Q1,SD_Q1,Median_Q1)  
names(stat_Q1)=c("state","mean","sd","median")
stat_Q1
```
```{r}
data(midwest)
attach(midwest)
midwest$prof_cnt <- percprof * popadults  
  
  # step 2,3 : Compute sum of raw professional# and total population by state
  tbl =  midwest  %>%
    group_by(state) %>%
    summarise(sum_adult =sum(popadults) , 
              sum_prof = sum(prof_cnt),
              perc_prof = sum(prof_cnt)/sum(popadults))
  print(tbl)
  
  # step 4 : Plot the data
  ggplot(tbl, aes(x=reorder(tbl$state,tbl$perc_prof), y =tbl$perc_prof)) + 
    geom_bar(stat='identity', aes(fill=state)) +
    ylab("% professionals") +
    scale_x_discrete("state") +
    geom_text(aes(label= round(tbl$perc_prof,2)), vjust=2) +
    ggtitle("% professionals by state ")

```
```{r}
data(midwest)
attach(midwest)
  midwest$hsd_cnt = perchsd * popadults
  midwest$college_cnt = percollege * popadults
  
  # compute % hsd and %college over adult population
  midwest$perchsd_adultpop = (perchsd * popadults)/popadults
  midwest$percollege_adultpop = (percollege * popadults)/popadults
  attach(midwest)
  
  # plot %hsd vs %college (over adult pop)
  qplot(perchsd, percollege, data=midwest , color=state, 
        main= "%hsd vs %college over Adult poplation")
  cor.test(perchsd, percollege)
  
  
  # plot %hsd vs %college for WI and IL only
  qplot(perchsd_adultpop, percollege_adultpop, data=subset(midwest, (state=='WI' | state=='IL')) , 
        color=state, main= "%hsd vs %college over Total poplation") + facet_wrap(~state)
  
  # plot %hsd vs %college and facet_wrap by state
  qplot(perchsd_adultpop, percollege_adultpop, data=midwest , 
        main="% hsd vs % college by state") + 
    geom_smooth()+
    xlab(" % high school diploma") +
    ylab(" % College graduates") +
    geom_vline(xintercept = 75, linetype = "dotdash", color='purple') +
    geom_hline(yintercept = 20, linetype = "dotdash", color='purple') +
    facet_wrap(~state)
  
  #summarize stats by state
  tbl_2 = midwest %>%
    group_by(state)%>%
    summarize(sum_pop =sum(popadults),
              sum_hsd = sum(hsd_cnt),
              sum_college = sum(college_cnt),
              perc_hsd = sum(hsd_cnt)/sum(popadults),
              perc_college = sum(college_cnt)/sum(popadults),
              
              mean_hsd = mean(perchsd),
              median_hsd = median(perchsd),
              IQR_hsd = IQR(perchsd),
              sd_hsd = sd(perchsd),
              
              mean_college = mean(percollege),
              median_college = median(percollege),
              IQR_college = IQR(percollege),  
              cor = cor.test(perchsd,percollege)$estimate,
              sd_college = sd(percollege),
              count =n())
  
  print.data.frame(tbl_2,digits=3 )
                   
  # Plot aggregate %hsd and %college by state
  ggplot(tbl_2, aes(x=perc_hsd, y=perc_college)) + geom_point(aes(shape=state)) + 
    geom_label(aes(label=tbl_2$state), hjust=-.2) +
    ggtitle("%hsd vs. %College by state") +
    xlab(" % of High School diploma") +
    ylab("% of College graduates")
    
  l = c('state','perc_hsd','perc_college', 'median_hsd' , 'median_college', 'mean_hsd' , 'mean_college',
        'IQR_hsd', 'IQR_college' ,'cor')
  print.data.frame(tbl_2[,l], digits=3 )
  
  
  # boxplot - perchsd by state
  ggplot(midwest , aes(reorder(state, -perchsd, median) , perchsd)) + 
    geom_boxplot(aes(color=state)) +
    coord_flip()+
    scale_x_discrete("state") +
    ggtitle("% High School Diploma by state")
  
  # boxplot - percollege by state
  ggplot(midwest , aes(reorder(state, -percollege, median) , percollege)) + 
    geom_boxplot(aes(color=state)) +
    coord_flip()+
    scale_x_discrete("state") +
    ggtitle("% College graduates by state")
  
  by(perchsd,state,summary)
  by(percollege,state,summary)
  
  
  ## %hsd vs. college by metro 
  qplot(perchsd, percollege, data=midwest, main= "%hsd vs %college by metro") +
    geom_hline(yintercept = 20,linetype = "longdash", color='blue') + 
    facet_wrap(~inmetro)
  
  ## %below poverty vs. % hsd 
  qplot(percchildbelowpovert,perchsd, data=midwest, main= "%hsd vs % Child below poverty") +
    xlab("% Child below poverty") + ylab("% hsd") + geom_smooth(method=lm) + 
    geom_vline(xintercept = 20, linetype = "longdash", color='blue') +
    facet_wrap(~state)
  
  cor.test(perchsd,percbelowpoverty)
  cor.test(perchsd,percchildbelowpovert)
  
  qplot(percbelowpoverty,perchsd, data=midwest, main= "%hsd vs % below poverty") +
    xlab("% below poverty") + ylab("% hsd") +
    geom_vline(xintercept = 15, linetype = "longdash", color='blue') +
    geom_hline(yintercept = 80, linetype = "longdash", color='blue') +
    facet_wrap(~inmetro)
  
  ## %below poverty vs. %college
  qplot( percbelowpoverty,percollege, data=midwest, main= "%college vs % below poverty") +
    xlab("% below poverty") +  ylab("% College")+
    facet_wrap(~inmetro)
```
```{r}
data = mpg[, c('model', 'hwy', 'cty')]
corr = NULL
for(model in unique(data$model)){
  sub_data = data[data$model==model,]
  if(nrow(sub_data)>2){
    corr[[model]] = cor.test(sub_data$hwy, sub_data$cty)$estimate
  }
}
corr_df = data.frame(model=names(corr), cor=corr)
ggplot(data, aes(x=hwy, y=cty)) + 
  geom_point(aes(color=model), show.legend = FALSE) + 
  geom_text(data=corr_df, aes(label=round(cor,4)), x=-Inf, y=Inf, hjust=-0.2, vjust=1.2) + 
  facet_wrap(~model, ncol=6) + labs(x="Highway MPG", y="City MPG", title="Highway MPG vs. City MPG scatterplot by Car Model")
```

