---
title: 'Homework 2: Data Visualization Submit Assignment'
author: "Sridhar Sampath"
date: "9 February 2018"
output: html_document
---

```{r}
library(ggplot2)
# install.packages("magrittr")
# Instead of using transformation, magrittr package is used to group the data as per requirement.
library(magrittr)
# Required to use group_by functionality 
library(dplyr)

# Load the midwest data
data(midwest)
ggplot(midwest , aes(reorder(state, -percprof, median) , percprof)) + 
    geom_boxplot(aes(color=state)) +
    scale_x_discrete("States") +
    ggtitle("Percentage of people with Professional Education")

# transform and group the data
mdwst = midwest %>% group_by(state) %>% 
                    summarize(minPercprof = min(percprof), 
                    q1Percprof = quantile(percprof, 0.25), 
                    meanPercprof = mean(percprof), 
                    medianPercprof = median(percprof), 
                    q3Percprof = quantile(percprof, 0.75), 
                    maxPercprof = max(percprof),
                    stdPercprof = sd(percprof))

print(mdwst)

# The number of professional in the each state
midwest$percprofdist = midwest$percprof * midwest$poptotal

# Create a table to contain total professional and their percentage across states
mdwst_dist =  midwest  %>% group_by(state) %>% 
  summarise(poptotal_states =sum(poptotal) , 
            percprofdist_states = sum(percprofdist),
            percprof_states = sum(percprofdist)/sum(poptotal))
print(mdwst_dist)

#  If you want the heights of the bars to represent values in the data, use stat="identity" and map a value to the y aesthetic.

ggplot(mdwst_dist, aes(x=reorder(mdwst_dist$state,mdwst_dist$percprof_states), y =mdwst_dist$percprof_states)) + 
    geom_bar(stat='identity', aes(fill=state)) +
    ylab("Percentage of professionals") +
    scale_x_discrete("state") +
    geom_text(aes(label= round(mdwst_dist$percprof_states,2))) +
    ggtitle("Percentage of professionals by state ")
```

2. School and College Education by State [20 points]

```{r}
data(midwest)
#install.packages("GGally")
library(GGally)
schcoledu = data.frame(midwest$perchsd,midwest$percollege,midwest$state)
ggpairs(schcoledu)

ggplot(midwest, aes(reorder(state, -perchsd, median), perchsd)) +
geom_boxplot() +
coord_flip() +
scale_x_discrete("State")

# a boxplot of percollege vs. state
ggplot(midwest, aes(reorder(state, -percollege, median), percollege)) +
geom_boxplot() +
coord_flip() +
scale_x_discrete("State")

#plot perchsd vs. percollege
qplot(x=perchsd,y=percollege,data=midwest,xlab="perchsd", ylab="percollege",col=state)
qplot(x=perchsd,y=percollege,data=midwest,xlab="perchsd", ylab="percollege",col=state, facets =state~.)

# transform and group the data
mdwst = midwest %>% group_by(state) %>% 
                    summarize(minPerchsd = min(perchsd), 
                    q1Perchsd = quantile(perchsd, 0.25), 
                    meanPerchsd = mean(perchsd), 
                    medianPerchsd = median(perchsd), 
                    q3Perchsd = quantile(perchsd, 0.75), 
                    maxPerchsd = max(perchsd),
                    stdPerchsd = sd(perchsd),
                    minPerchsd = min(percollege), 
                    q1Perchsd = quantile(percollege, 0.25), 
                    meanPercollege = mean(percollege), 
                    medianPercollege = median(percollege), 
                    q3Percollege = quantile(percollege, 0.75), 
                    maxPercollege = max(percollege),
                    stdPercollege = sd(percollege),
                    corr = cor.test(perchsd, percollege))$estimate
print(mdwst)

```

